### ISSUE TITLE
Base64 encoding issue

### ISSUE THREAD

**Issue by ivanweiler** [B-Matt/Scrapbook-Project#1]
Hello there,

First, it's best to resize image to required preview size, before applying filter (it will be faster to apply filter to smaller image instead original one):
```
$image->resize(292, 292);
//$image->fit(292); (better way, horizontal image will be cropped in center)
```
http://image.intervention.io/api/fit

To fix base64, replace current echo at:
https://github.com/B-Matt/Scrapbook-Project/blob/master/app/Helpers/ImageFilter.php#L53

with:
```
echo $image->encode('data-url');
```

We'll talk tomorrow, regards ;)

**Comment by B-Matt** [comment]
It works great. Thanks!
